module.exports = {
    INIT: "init",
    ACTION: "action",
    ADMIN: "admin",
    CHAT: "chat",
    CONNECT: "connection",
    DISCONNECT: "disconnecting",
    MESSAGE: "message",
    MOTD: "motd",
    PLAYERLISTREQUEST: "playerlistrequest",
    TRANSFER: "transfer",
    RECORDS: "records",
    JOIN: "join",
    LEAVE: "leave",
    JOINROOM: "join-room",
    LEAVEROOM: "leave-room",
};
